FROM node:20-alpine AS base
RUN apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev vips-dev git
WORKDIR /opt/app

FROM base AS deps
COPY package.json package-lock.json ./
RUN npm ci

FROM deps AS builder
WORKDIR /opt/app
COPY . .
ENV NODE_ENV=production
RUN npm run build

FROM base AS production
ENV NODE_ENV=production
WORKDIR /opt/app

COPY --from=builder /opt/app/node_modules ./node_modules
COPY --from=builder /opt/app/package.json ./package.json
COPY --from=builder /opt/app/dist ./dist
COPY --from=builder /opt/app/public ./public
COPY --from=builder /opt/app/config ./config
COPY --from=builder /opt/app/src ./src
COPY --from=builder /opt/app/database ./database
COPY --from=builder /opt/app/tsconfig.json ./tsconfig.json

RUN chown -R node:node /opt/app
USER node

EXPOSE 1337
CMD ["npm", "run", "start"]
